name: Cypress and Percy Tests

# on:
 # push:
 #   branches: [ main ]
 # pull_request:
 #   branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Clear Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/*.lock') }}
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      # Führt die Installation nur beim ersten Mal aus
      if: steps.clear_cache.outputs.cache-hit != 'true'

    - name: Install Dependencies
      run: npm install
      # Führt die Installation nur beim ersten Mal aus
      if: steps.clear_cache.outputs.cache-hit != 'true'

    - name: Set Percy Token
      run: echo "PERCY_TOKEN=$PERCY_TOKEN" >> $GITHUB_ENV
      env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        
    - name: Run Cypress and Percy Tests
      run: npx percy exec -- cypress run
      env:
        CYPRESS_BASE_URL: 'https://ikrabau.de'
