name: Cypress and Percy Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Clear Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/*.lock') }}
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Set Percy Token
      run: echo "PERCY_TOKEN=web_'code'" >> $GITHUB_ENV
        
    - name: Run Cypress and Percy Tests
      run: npx percy exec -- cypress run
      env:
        PERCY_TOKEN: ${{ env.PERCY_TOKEN }}
        CYPRESS_BASE_URL: 'https://ikrabau.de'
